// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeddySwap.Sink.Data;

#nullable disable

namespace TeddySwap.Sink.Data.Migrations
{
    [DbContext(typeof(TeddySwapNftSinkDbContext))]
    [Migration("20230320044205_AdInitialCreate")]
    partial class AdInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeddySwap.Common.Models.Asset", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("TxOutputHash")
                        .HasColumnType("text");

                    b.Property<decimal>("TxOutputIndex")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("PolicyId", "Name", "TxOutputHash", "TxOutputIndex");

                    b.HasIndex("TxOutputHash", "TxOutputIndex");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Block", b =>
                {
                    b.Property<string>("BlockHash")
                        .HasColumnType("text");

                    b.Property<decimal>("BlockNumber")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Epoch")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<IEnumerable<ulong>>("InvalidTransactions")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Slot")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("VrfKeyhash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BlockHash");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.MintTransaction", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text");

                    b.Property<string>("TokenName")
                        .HasColumnType("text");

                    b.Property<string>("AsciiTokenName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TransactionIndex")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("PolicyId", "TokenName");

                    b.HasIndex("TransactionHash", "TransactionIndex");

                    b.ToTable("MintTransactions");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.NftOwner", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text");

                    b.Property<string>("TokenName")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NftPolicyId")
                        .HasColumnType("text");

                    b.Property<string>("NftTokenName")
                        .HasColumnType("text");

                    b.HasKey("PolicyId", "TokenName");

                    b.HasIndex("NftPolicyId", "NftTokenName");

                    b.ToTable("NftOwners");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Transaction", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<decimal>("Index")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Blockhash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.HasKey("Hash", "Index");

                    b.HasIndex("Blockhash");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.TxOutput", b =>
                {
                    b.Property<string>("TxHash")
                        .HasColumnType("text");

                    b.Property<decimal>("Index")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("DatumCbor")
                        .HasColumnType("text");

                    b.Property<decimal>("TxIndex")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("TxHash", "Index");

                    b.HasIndex("TxHash", "TxIndex");

                    b.ToTable("TxOutputs");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Asset", b =>
                {
                    b.HasOne("TeddySwap.Common.Models.TxOutput", "TxOutput")
                        .WithMany("Assets")
                        .HasForeignKey("TxOutputHash", "TxOutputIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TxOutput");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.MintTransaction", b =>
                {
                    b.HasOne("TeddySwap.Common.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionHash", "TransactionIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.NftOwner", b =>
                {
                    b.HasOne("TeddySwap.Common.Models.MintTransaction", "Nft")
                        .WithMany()
                        .HasForeignKey("NftPolicyId", "NftTokenName");

                    b.Navigation("Nft");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Transaction", b =>
                {
                    b.HasOne("TeddySwap.Common.Models.Block", "Block")
                        .WithMany("Transactions")
                        .HasForeignKey("Blockhash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.TxOutput", b =>
                {
                    b.HasOne("TeddySwap.Common.Models.Transaction", "Transaction")
                        .WithMany("Outputs")
                        .HasForeignKey("TxHash", "TxIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Block", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Transaction", b =>
                {
                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.TxOutput", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
