// <auto-generated />
using System.Collections.Generic;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeddySwap.Sink.Data;

#nullable disable

namespace TeddySwap.Sink.Data.Migrations
{
    [DbContext(typeof(TeddySwapSinkDbContext))]
    [Migration("20230304134024_UpdateNullableBatcherAddress")]
    partial class UpdateNullableBatcherAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeddySwap.Common.Models.AddressVerification", b =>
                {
                    b.Property<string>("TestnetAddress")
                        .HasColumnType("text");

                    b.Property<string>("MainnetAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MainnetSignedData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestnetSignedData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TestnetAddress");

                    b.ToTable("AddressVerifications");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Asset", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("TxOutputHash")
                        .HasColumnType("text");

                    b.Property<decimal>("TxOutputIndex")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("PolicyId", "Name", "TxOutputHash", "TxOutputIndex");

                    b.HasIndex("TxOutputHash", "TxOutputIndex");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.BlacklistedAddress", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.HasKey("Address");

                    b.ToTable("BlacklistedAddresses");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Block", b =>
                {
                    b.Property<string>("BlockHash")
                        .HasColumnType("text");

                    b.Property<decimal>("BlockNumber")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Epoch")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<IEnumerable<ulong>>("InvalidTransactions")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Slot")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("VrfKeyhash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BlockHash");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Order", b =>
                {
                    b.Property<string>("TxHash")
                        .HasColumnType("text");

                    b.Property<decimal>("Index")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("AssetLq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetX")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetY")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BatcherAddress")
                        .HasColumnType("text");

                    b.Property<string>("Blockhash")
                        .HasColumnType("text");

                    b.Property<BigInteger>("Liquidity")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderBase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("OrderDatum")
                        .HasColumnType("bytea");

                    b.Property<BigInteger>("OrderLq")
                        .HasColumnType("numeric");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer");

                    b.Property<BigInteger>("OrderX")
                        .HasColumnType("numeric");

                    b.Property<BigInteger>("OrderY")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("PoolDatum")
                        .HasColumnType("bytea");

                    b.Property<string>("PoolNft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<BigInteger>("ReservesX")
                        .HasColumnType("numeric");

                    b.Property<BigInteger>("ReservesY")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Slot")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TxHash", "Index");

                    b.HasIndex("Blockhash");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Price", b =>
                {
                    b.Property<string>("TxHash")
                        .HasColumnType("text");

                    b.Property<decimal>("Index")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("PriceX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceY")
                        .HasColumnType("numeric");

                    b.HasKey("TxHash", "Index");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Transaction", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<decimal>("Index")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Blockhash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Hash", "Index");

                    b.HasIndex("Blockhash");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.TxOutput", b =>
                {
                    b.Property<string>("TxHash")
                        .HasColumnType("text");

                    b.Property<decimal>("Index")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("DatumCbor")
                        .HasColumnType("text");

                    b.Property<decimal>("TxIndex")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("TxHash", "Index");

                    b.HasIndex("TxHash", "TxIndex");

                    b.ToTable("TxOutputs");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Asset", b =>
                {
                    b.HasOne("TeddySwap.Common.Models.TxOutput", "TxOutput")
                        .WithMany("Assets")
                        .HasForeignKey("TxOutputHash", "TxOutputIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TxOutput");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Order", b =>
                {
                    b.HasOne("TeddySwap.Common.Models.Block", "Block")
                        .WithMany("Orders")
                        .HasForeignKey("Blockhash")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Block");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Price", b =>
                {
                    b.HasOne("TeddySwap.Common.Models.Order", "Order")
                        .WithOne("Price")
                        .HasForeignKey("TeddySwap.Common.Models.Price", "TxHash", "Index")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Transaction", b =>
                {
                    b.HasOne("TeddySwap.Common.Models.Block", "Block")
                        .WithMany("Transactions")
                        .HasForeignKey("Blockhash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.TxOutput", b =>
                {
                    b.HasOne("TeddySwap.Common.Models.Transaction", "Transaction")
                        .WithMany("Outputs")
                        .HasForeignKey("TxHash", "TxIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Block", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Order", b =>
                {
                    b.Navigation("Price");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.Transaction", b =>
                {
                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("TeddySwap.Common.Models.TxOutput", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
