[source]
type = "N2C"
address = ["Unix", "/Users/rjlacanlale/Desktop/projects/cardano-preview/ipc/node.socket"]
magic = "preview"

[source.intersect]
type = "Origin"

[[filters]]
type = "Fingerprint"

[[filters]]
type = "Selection"

[filters.check]
predicate = "variant_in"
argument = ["TxOutput", "Block", "TxInput", "StakeDelegation"]

[sink]
type = "Webhook"
url = "http://localhost:5087/ourawebhook/"
timeout = 30000
error_policy = "Continue"

[source.mapper]
include_transaction_details = true

[cursor]
type = "File"
path = "cursor"