[source]
type = "N2C"
address = ["Unix", "/home/jmqb/cardano-preview/ipc/node.socket"]
magic = "preview"
min_depth = 10

[source.intersect]
type = "Origin"

[[filters]]
type = "Fingerprint"

[[filters]]
type = "Selection"

[filters.check]
predicate = "variant_in"
argument = ["TxOutput", "Block", "TxInput", "RollBack", "PoolRegistration"]

[sink]
type = "Webhook"
url = "http://localhost:5087/ourawebhook/"
timeout = 9999999999999
error_policy = "Exit"

[source.mapper]
include_transaction_details = true

[cursor]
type = "File"
path = "cursor"

[sink.retry_policy]
max_retries = 0
backoff_unit =  5000
backoff_factor = 2
max_backoff = 100000