[source]
type = "N2C"
address = ["Unix", "/ipc/node.socket"]
magic = "preview"

[source.intersect]
type = "Origin"

[[filters]]
type = "Selection"

[filters.check]
predicate = "any_of"

[[filters.check.argument]]
predicate = "variant_in"
argument = ["Block"]

[sink]
type = "Webhook"
url = "http://localhost:1337/ourawebhook/"
timeout = 9999999999999
error_policy = "Exit"

[source.mapper]
include_block_details = true
include_transaction_details = true

[cursor]
type = "File"
path = "cursor"

[sink.retry_policy]
max_retries = 0
backoff_unit = 5000
backoff_factor = 2
max_backoff = 100000