openapi: 3.0.0
info:
    version: 1.0.0
    title: Conclave Sink API
    description: To follow

servers:
    - url: http://localhost:5087

components:
    parameters:
        OrderByQuery:
            name: ascendingOrder
            in: query
            description: Determines the order of the result
            schema:
                type: boolean
                default: true
        ConclaveQuery:
            name: isConclave
            in: query
            description: Get only conclave pools
            schema:
                type: boolean
                default: false
        LimitQuery:
            name: limit
            in: query
            description: Count limit of the results
            schema:
                type: integer
                minimum: 1
                maximum: 1000
                default: 100
        CursorQuery:
            name: cursor
            in: query
            description: Determines which values to fetch next
            schema:
                type: string
        FilterQuery:
            name: filter
            in: query
            description: Specific key to filter
            schema:
                type: string
        StakeAddressQuery:
            name: stakeAddress
            in: query
            description: Stake address to prioritize in sorting
            schema:
                type: string
        FromEpochQuery:
            name: fromEpoch
            in: query
            description: Epoch to fetch
            schema:
                type: integer
                minimum: 0
                default: 0
        ToEpochQuery:
            name: toEpoch
            in: query
            description: Epoch to fetch
            schema:
                type: integer
                minimum: 0
                default: 0
        StakeAddressPath:
            name: stakeAddress
            in: path
            required: true
            description: Stake address to fetch
            schema:
                type: string
        PoolIdPath:
            name: poolId
            in: path
            required: true
            description: Pool to fetch
            schema:
                type: string

    schemas:
        Cursor:
            type: object
            properties:
                next:
                    type: string
                    example: 'next_af0248bbc'
                prev:
                    type: string
                    example: 'prev_af0248bbc'
        Pool:
            type: object
            properties:
                name:
                    type: string
                    example: ADA Philippines
                ticker:
                    type: string
                    example: ADAPH
                description:
                    type: string
                    example: '#1 Cardano Stake Pool in the Philippines'
                blocks:
                    type: integer
                    example: 10
                saturation:
                    type: number
                    example: 50.5
                pledge:
                    type: integer
                    example: 100000000
                interest:
                    type: integer
                    example: 10
        Pools:
            type: array
            items:
                $ref: '#/components/schemas/Pool'
            example:
                - name: ADA Philippines
                  ticker: ADAPH
                  description: '#1 Cardano Stake Pool in the Philippines'
                  blocks: 10
                  saturation: 50.5
                  pledge: 1000000000
                - name: ADA Philippines
                  ticker: ADAPH
                  description: '#1 Cardano Stake Pool in the Philippines'
                  blocks: 10
                  saturation: 50.5
                  pledge: 1000000000
                  interest: 10
        BalanceByEpoch:
            type: object
            properties:
                epoch:
                    type: integer
                    example: 10
                lovelace:
                    type: integer
                    example: 10000000
                conclave:
                    type: integer
                    example: 10000000
        BalanceByEpochs:
            type: array
            items:
                $ref: '#/components/schemas/BalanceByEpoch'
            example:
                - epoch: 1
                  lovelace: 100000
                  conclave: 10000000
                - epoch: 2
                  lovelace: 200000
                  conclave: 2000000

    responses:
        200SuccessPools:
            description: Ok
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            results:
                                $ref: '#/components/schemas/Pools'
                            cursor:
                                $ref: '#/components/schemas/Cursor'

        200SuccessStakes:
            description: Ok
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/BalanceByEpochs'

        400Error:
            description: Invalid request
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                                example: Invalid request

paths:
    /pools:
        get:
            summary: Returns a list of pools with their metadata
            parameters:
                - $ref: '#/components/parameters/LimitQuery'
                - $ref: '#/components/parameters/CursorQuery'
                - $ref: '#/components/parameters/FilterQuery'
                - $ref: '#/components/parameters/StakeAddressQuery'
                - $ref: '#/components/parameters/ConclaveQuery'
                - $ref: '#/components/parameters/OrderByQuery'
            responses:
                '200':
                    $ref: '#/components/responses/200SuccessPools'
                '400':
                    $ref: '#/components/responses/400Error'

    /accounts/{stakeAddress}/stakes:
        get:
            summary: "Returns a list of stakeAddress' staking history"
            parameters:
                - $ref: '#/components/parameters/StakeAddressPath'
                - $ref: '#/components/parameters/FromEpochQuery'
                - $ref: '#/components/parameters/ToEpochQuery'
            responses:
                '200':
                    $ref: '#/components/responses/200SuccessStakes'
                '400':
                    $ref: '#/components/responses/400Error'
