openapi: 3.0.0
info:
    version: 1.0.0
    title: Conclave Sink API
    description: To follow

servers:
    - url: http://localhost:5087

components:
    parameters:
        PageQuery:
            name: page
            in: query
            description: Specific page to fetch
            schema:
                type: integer
                minimum: 1
                default: 1
        CountQuery:
            name: count
            in: query
            description: Item count limit per page
            schema:
                type: integer
                minimum: 1
                default: 100
        SearchKeyQuery:
            name: searchKey
            in: query
            description: Search key to use as filter
            schema:
                type: string
        StakeAddressQuery:
            name: stakeAddress
            in: query
            description: Stake address to prioritize in sorting
            schema:
                type: string
        FromEpochQuery:
            name: fromEpoch
            in: query
            description: Epoch to fetch
            schema:
                type: integer
                minimum: 0
                default: 0
        ToEpochQuery:
            name: toEpoch
            in: query
            description: Epoch to fetch
            schema:
                type: integer
                minimum: 0
                default: 0
        StakeAddressPath:
            name: stakeAddress
            in: path
            required: true
            description: Stake address to fetch
            schema:
                type: string
        PoolIdPath:
            name: poolId
            in: path
            required: true
            description: Pool to fetch
            schema:
                type: string

    schemas:
        Pool:
            type: object
            properties:
                name:
                    type: string
                    example: ADA Philippines
                ticker:
                    type: string
                    example: ADAPH
                description:
                    type: string
                    example: '#1 Cardano Stake Pool in the Philippines'
                blocks:
                    type: integer
                    example: 10
                saturation:
                    type: number
                    example: 50.5
                pledge:
                    type: integer
                    example: 100000000
                interest:
                    type: integer
                    example: 10
        Pools:
            type: array
            items:
                $ref: '#/components/schemas/Pool'
            example:
                - name: ADA Philippines
                  ticker: ADAPH
                  description: '#1 Cardano Stake Pool in the Philippines'
                  blocks: 10
                  saturation: 50.5
                  pledge: 1000000000
                  interest: 10
                - name: ADA Philippines
                  ticker: ADAPH
                  description: '#1 Cardano Stake Pool in the Philippines'
                  blocks: 10
                  saturation: 50.5
                  pledge: 1000000000
                  interest: 10
        BalanceByEpoch:
            type: object
            properties:
                epoch:
                    type: integer
                    example: 10
                lovelace:
                    type: integer
                    example: 10000000
                conclave:
                    type: integer
                    example: 10000000
        BalanceByEpochs:
            type: array
            items:
                $ref: '#/components/schemas/BalanceByEpoch'
            example:
                - epoch: 1
                  lovelace: 100000
                  conclave: 10000000
                - epoch: 2
                  lovelace: 200000
                  conclave: 2000000

    responses:
        200SuccessPools:
            description: Ok
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Pools'

        200SuccessStakes:
            description: Ok
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/BalanceByEpochs'

        400Error:
            description: Invalid request
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                                example: Invalid request

paths:
    /pools:
        get:
            summary: Returns a list of pools with their metadata
            parameters:
                - $ref: '#/components/parameters/PageQuery'
                - $ref: '#/components/parameters/CountQuery'
                - $ref: '#/components/parameters/SearchKeyQuery'
                - $ref: '#/components/parameters/StakeAddressQuery'
            responses:
                '200':
                    $ref: '#/components/responses/200SuccessPools'
                '400':
                    $ref: '#/components/responses/400Error'
    /pools/conclave:
        get:
            summary: Returns a list of conclave pools with their metadata
            parameters:
                - $ref: '#/components/parameters/PageQuery'
                - $ref: '#/components/parameters/CountQuery'
                - $ref: '#/components/parameters/SearchKeyQuery'
                - $ref: '#/components/parameters/StakeAddressQuery'
            responses:
                '200':
                    $ref: '#/components/responses/200SuccessPools'
                '400':
                    $ref: '#/components/responses/400Error'
    /pools/{poolId}/stakes:
        get:
            summary: "Returns a list of pool's total stake history"
            parameters:
                - $ref: '#/components/parameters/PoolIdPath'
                - $ref: '#/components/parameters/FromEpochQuery'
                - $ref: '#/components/parameters/ToEpochQuery'
            responses:
                '200':
                    $ref: '#/components/responses/200SuccessStakes'
                '400':
                    $ref: '#/components/responses/400Error'

    /accounts/{stakeAddress}/stakes:
        get:
            summary: "Returns a list of stakeAddress' staking history"
            parameters:
                - $ref: '#/components/parameters/StakeAddressPath'
                - $ref: '#/components/parameters/FromEpochQuery'
                - $ref: '#/components/parameters/ToEpochQuery'
            responses:
                '200':
                    $ref: '#/components/responses/200SuccessStakes'
                '400':
                    $ref: '#/components/responses/400Error'
